services:
  monitor:
    build: .
    image: my-script
    command: ["/usr/local/bin/script.sh"]
    environment:
      MAX_ITERATIONS: "3"
    volumes:
      - ./out:/var/www
      - /etc/localtime:/etc/localtime:ro
